"""Create table BalanceChange

Revision ID: 17c7384f6409
Revises: f37b067cf04c
Create Date: 2024-02-26 17:23:51.460110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c7384f6409'
down_revision: Union[str, None] = 'f37b067cf04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balancechange',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('date_time_creation', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('operation_type', sa.Enum('WD', 'DT', name='transactiontype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balancechange')
    # ### end Alembic commands ###
